name: integration
on:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: install
      run: |
        make install
        brew reinstall git || true
        brew link --overwrite git
        brew install git-svn mercurial fossil breezy darcs
        brew upgrade git-svn mercurial fossil breezy darcs
    - name: test
      run: PATH=$HOME/bin:$PATH ./misc/author/integration_test.sh
